// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ExpSystem","status":true,"description":"A small review of the rewards system.\r\nRequires: TacticsSystem.js","parameters":{"attack exp formula":"b.exp() / 10"}},
{"name":"TacticsSystem","status":true,"description":"A Tactical Battle System like Fire Emblem series.\r\nRequires: Selector.png in img/system.","parameters":{"cursor speed":"2","grid opacity":"30","move points":"5","action range":"diamond 1","wait skill id":"7","move scope color":"#0066CC","ally scope color":"#008000","enemy scope color":"#B22222","display manager":"","show hp gauge":"1","show state icon":"1","show battle start":"1","duration start sprite":"300","show information window":"1","text manager":"","battle start term":"Battle Start","end turn term":"End Turn","damage term (abbr.)":"Dmg","recover term (abbr.)":"Rcv","drain term (abbr.)":"Drn","hit rate term (abbr.)":"Hit","critical rate term (abbr.)":"Cri","wait command name":"Wait","switches manager":"","battle start id":"1","player phase id":"2","enemy phase id":"3","variables manager":"","current phase id":"1","current player phase id":"2","current battle phase id":"3","turn count id":"4"}},
{"name":"BattlePreparation","status":true,"description":"Add-on to manage unit party before the battle.\nRequires: TacticsSystem.js.","parameters":{"start scope color":"#FFD700","start battle term":"Start Battle","preparation phase id":"4"}},
{"name":"Calista","status":true,"description":"Just utilities for the demo. Not for the Tactics System!","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"TacticsConfig","status":true,"description":"Adds basic configuration data.\nRequires: TacticsSystem.js","parameters":{}},
{"name":"MouseSystem","status":true,"description":"Add features for control with the mouse.\nRequires: TacticsSystem.js.","parameters":{}},
{"name":"CombatScene","status":true,"description":"Add-on to display the combat animation scene.\r\nRequires: TacticsSystem.js","parameters":{"start transition delay":"30","end transition delay":"30"}}
];
