// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Smart Path (MV)","status":true,"description":"Allows events or players to do smart Pathfinding","parameters":{}},
{"name":"TSOTSrpg_managers","status":false,"description":"","parameters":{}},
{"name":"TSOTSrpg_objects","status":true,"description":"","parameters":{}},
{"name":"TSOTSrpg_scenes","status":true,"description":"","parameters":{}},
{"name":"TSOTSrpg_sprites","status":true,"description":"","parameters":{}},
{"name":"console boot","status":true,"description":"Shows the developer console on boot.","parameters":{"Console Width":"800","Console Height":"300","Console X-Position":"0","Console Y-Position":"0","Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}},
{"name":"Tactics_Basic","status":true,"description":"A Tactical Battle System designed for RPG Maker.","parameters":{"Basic Parameters":"","Selector File":"Selector","Selector Speed":"2","Grid Opacity":"30","Move Points":"5","Action Range":"1","Wait Skill Id":"7","Auto Turn End":"true","Tiles Color":"","Move Scope Color":"#0066CC","Ally Scope Color":"#008000","Enemy Scope Color":"#B22222","Display Manager":"","Show Hp Gauge":"true","Show State Icon":"true","Show Battle Start":"true","Duration Start Sprite":"300","Show Information Window":"true","Fade Out End":"true","Set Transparent Unit":"true","Show Face Unit":"true","Text Manager":"","Battle Start Term":"Battle Start","End Turn Term":"End Turn","Damage Term":"Damage","Recover Term":"Recover","Drain term":"Drain","Hit Rate Term":"Hit Rate","Critical Rate Term":"Cri Rate","Wait Command Name":"Wait","Progression Manager":"","Battle Start Id":"1","Player Phase Id":"2","Enemy Phase Id":"3","Current Phase Id":"1","Current Player Phase Id":"2","Current Battle Phase Id":"3","Turn Count Id":"4"}},
{"name":"Tactics_Combat","status":true,"description":"Add-on to display the combat animation scene.\r\nRequires: TacticsSystem.js","parameters":{}},
{"name":"Tactics_Mouse","status":true,"description":"Add features for control with the mouse.\nRequires: TacticsSystem.js.","parameters":{}},
{"name":"Tactics_Prepa","status":true,"description":"Add-on to manage unit party before the battle.\nRequires: Tactics_Basic.js.","parameters":{"Start Scope Color":"#FFD700","Start Battle Term":"Start Battle","Preparation Phase Id":"4","Open Prepa Menu":"true"}},
{"name":"Tactics_Rewards","status":true,"description":"Review of the rewards for tactics battle.\r\nRequires: TacticsSystem.js","parameters":{"Attack Exp Formula":"b.exp() / 10"}},
{"name":"Tactics_Teleport","status":true,"description":"A teleportation skill for an ally or an enemy requested by strik156.\nRequires: TacticsSystem.js.","parameters":{"Teleport Distance Formula":"a.mat/2"}}
];
